version: '3.9'
services:
  db:
    container_name: poc-elastic-db
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  back:
    container_name: poc-elastic-back
    build: .
    ports:
      - "8080:8080"
