version: '3.9'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: db
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
